blank_issues_enabled: true
contact_links:
  - name: 💬 Comunidad y Discusiones
    url: https://github.com/TuGeek/ProVacuno-feedback/discussions
    about: Para conversaciones generales, ideas y preguntas abiertas
